<?php
/**
 * InvoiceResponseDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * e-MCF
 *
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceResponseDtoTest Class Doc Comment
 *
 * @category    Class
 * @description InvoiceResponseDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceResponseDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceResponseDto"
     */
    public function testInvoiceResponseDto()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "ta"
     */
    public function testPropertyTa()
    {
    }

    /**
     * Test attribute "tb"
     */
    public function testPropertyTb()
    {
    }

    /**
     * Test attribute "tc"
     */
    public function testPropertyTc()
    {
    }

    /**
     * Test attribute "td"
     */
    public function testPropertyTd()
    {
    }

    /**
     * Test attribute "taa"
     */
    public function testPropertyTaa()
    {
    }

    /**
     * Test attribute "tab"
     */
    public function testPropertyTab()
    {
    }

    /**
     * Test attribute "tac"
     */
    public function testPropertyTac()
    {
    }

    /**
     * Test attribute "tad"
     */
    public function testPropertyTad()
    {
    }

    /**
     * Test attribute "tae"
     */
    public function testPropertyTae()
    {
    }

    /**
     * Test attribute "taf"
     */
    public function testPropertyTaf()
    {
    }

    /**
     * Test attribute "hab"
     */
    public function testPropertyHab()
    {
    }

    /**
     * Test attribute "had"
     */
    public function testPropertyHad()
    {
    }

    /**
     * Test attribute "vab"
     */
    public function testPropertyVab()
    {
    }

    /**
     * Test attribute "vad"
     */
    public function testPropertyVad()
    {
    }

    /**
     * Test attribute "aib"
     */
    public function testPropertyAib()
    {
    }

    /**
     * Test attribute "ts"
     */
    public function testPropertyTs()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "error_desc"
     */
    public function testPropertyErrorDesc()
    {
    }
}
