<?php
/**
 * StatusResponseDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * e-MCF
 *
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StatusResponseDtoTest Class Doc Comment
 *
 * @category    Class
 * @description StatusResponseDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StatusResponseDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StatusResponseDto"
     */
    public function testStatusResponseDto()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "ifu"
     */
    public function testPropertyIfu()
    {
    }

    /**
     * Test attribute "nim"
     */
    public function testPropertyNim()
    {
    }

    /**
     * Test attribute "token_valid"
     */
    public function testPropertyTokenValid()
    {
    }

    /**
     * Test attribute "server_date_time"
     */
    public function testPropertyServerDateTime()
    {
    }

    /**
     * Test attribute "pending_requests_count"
     */
    public function testPropertyPendingRequestsCount()
    {
    }

    /**
     * Test attribute "pending_requests_list"
     */
    public function testPropertyPendingRequestsList()
    {
    }
}
