<?php
/**
 * TaxGroupsDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * e-MCF
 *
 * DGI Bénin - Tous droits réservés
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TaxGroupsDtoTest Class Doc Comment
 *
 * @category    Class
 * @description TaxGroupsDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaxGroupsDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TaxGroupsDto"
     */
    public function testTaxGroupsDto()
    {
    }

    /**
     * Test attribute "a"
     */
    public function testPropertyA()
    {
    }

    /**
     * Test attribute "b"
     */
    public function testPropertyB()
    {
    }

    /**
     * Test attribute "c"
     */
    public function testPropertyC()
    {
    }

    /**
     * Test attribute "d"
     */
    public function testPropertyD()
    {
    }

    /**
     * Test attribute "e"
     */
    public function testPropertyE()
    {
    }

    /**
     * Test attribute "f"
     */
    public function testPropertyF()
    {
    }

    /**
     * Test attribute "aib_a"
     */
    public function testPropertyAibA()
    {
    }

    /**
     * Test attribute "aib_b"
     */
    public function testPropertyAibB()
    {
    }
}
